name: docker tests

on:
  workflow_dispatch:
jobs:
  version_tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
      with:
        repository: timmyteo/dep-scan
        ref: feature/issue-100
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip setuptools
        python3 -m pip install .[dev]
        npm install -g @cyclonedx/cdxgen
    - name: Run pytest tests
      run: |
        depscan -i .
      env:
        FETCH_LICENSE: true
        PYTHONPATH: "."
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VDB_HOME: "vdb_data"
