name: Test depscan action

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: juice-shop/juice-shop

      - name: Run depscan action
        uses: AppThreat/dep-scan-action@18d1612a791591135d1a6514c5e40fdbb8f6f86a
        with:
          thank_you: "I have not donated."
