name: Test depscan action

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: juice-shop/juice-shop

      - name: Run depscan action
        uses: AppThreat/dep-scan-action@d9664b88b20ad7234f958a9a2c9f0bc208216d7c
        with:
          thank_you: "I have not donated."
