name: Test depscan action

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: juice-shop/juice-shop

      - name: Run depscan action
        uses: AppThreat/dep-scan-action@4410d41597deb9afae1e3ccb61d535b59ad1eae6
        with:
          thank_you: "I have not donated."
