name: Test depscan action

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: juice-shop/juice-shop

      - name: Run depscan action
        uses: AppThreat/dep-scan-action@b29566f6deff3ed5ae35a88aec269b78a3634bfe
        with:
          thank_you: "I have not donated."
